# Looks like reusable workflows must reside in the .github/workflows folder to be usable.
# Example discussion - https://github.com/actions/runner/issues/1493
name: Reusable workflow example

on: 
  workflow_call:
    inputs:
      myENV_NAME:
        description: Environment to deploy to. Example, stage-us.
        required: true
        type: string

jobs:
  
  deploy_stage:
    name: Stage
    runs-on: ubuntu-latest
    strategy:
          matrix:
            runs-on: ${{ fromJSON(inputs.myENV_NAME) }}
    steps:
      - name: stage-${{ fromJSON(inputs.myENV_NAME) }}
        run: |
          echo "Hello Workflow!"
          echo "Deploying to ${{ fromJSON(inputs.myENV_NAME) }}"

  deploy_prod:
    name: Production
    runs-on: ubuntu-latest
    needs: deploy_stage
    strategy:
          matrix:
            runs-on: ${{ fromJSON(inputs.myENV_NAME) }}
    steps:
      - name: prod-${{ fromJSON(inputs.myENV_NAME) }}
        run: |
          echo "Hello Workflow!"
          echo "Deploying to ${{ fromJSON(inputs.myENV_NAME) }}"