# Looks like reusable workflows must reside in the .github/workflows folder to be usable.
# Example discussion - https://github.com/actions/runner/issues/1493
name: Reusable workflow example

# on:
#   workflow_call:
#     inputs:
#       username:
#         required: true
#         type: string
#     secrets:
#       token:
#         required: true

on: 
  workflow_call:
    

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/my-action
        # with:
        #   username: ${{ inputs.username }}
        #   token: ${{ secrets.token }}
        run: |
          echo "Hello Workflow!"