# Looks like reusable workflows must reside in the .github/workflows folder to be usable.
# Example discussion - https://github.com/actions/runner/issues/1493
name: Reusable workflow example

on: 
  workflow_call:
    inputs:
      myENV_NAME:
        description: Environment to deploy to. Example, stage-us.
        required: true
        type: string

jobs:
  
  deploy_stage:
    name: Stage
    strategy:
          matrix:
            myENV_NAME: ${{ fromJSON(inputs.myENV_NAME) }}
    runs-on: ubuntu-latest
    steps:
      - name: stage-${{ matrix.myENV_NAME }}
        run: |
          echo "Hello Workflow!"
          echo "Deploying to ${{ matrix.myENV_NAME }}"

  deploy_prod:
    name: Production
    strategy:
          matrix:
            myENV_NAME: ${{ fromJSON(inputs.myENV_NAME) }}
    runs-on: ubuntu-latest
    needs: deploy_stage
    environment: 'stage-${{ matrix.myENV_NAME }}'
    steps:
      - name: prod-${{ matrix.myENV_NAME }}
        run: |
          echo "Hello Workflow!"
          echo "Deploying to ${{ matrix.myENV_NAME }}"