# Looks like reusable workflows must reside in the .github/workflows folder to be usable.
# Example discussion - https://github.com/actions/runner/issues/1493
name: Reusable workflow example

# on:
#   workflow_call:
#     inputs:
#       username:
#         required: true
#         type: string
#     secrets:
#       token:
#         required: true

on: 
  workflow_call:
    inputs:
      myENV_NAME:
        description: Environment to deploy to. Example, stage-us.
        required: true
        type: string

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    strategy:
          matrix:
            runs-on: ${{ fromJSON(inputs.myENV_NAME) }}
    steps:
      - name: Test Flow
        # with:
        #   username: ${{ inputs.username }}
        #   token: ${{ secrets.token }}
        run: |
          echo "Hello Workflow!"
          echo "Deploying to ${{ fromJSON(inputs.myENV_NAME) }}"