name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  image_name: "my-python-api"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build an image from Dockerfile
      run: |
        docker build -t ${image_name}:${{ github.sha }} .
    
    - uses: azure/container-scan@v0.1
      with:
        image-name: my-image:my-tag
